import {summary,compare} from './stats.js';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x==null?'—':Number.isInteger(x)?x.toLocaleString():x.toFixed(2);
let rows=[],view='drivers',driver='',opponent='',race='',metric='wins';
const unique=(rs,k)=>[...new Set(rs.map(r=>r[k]).filter(Boolean))].sort();
function options(values,all){return (all?`<option value="">${all}</option>`:'')+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}
function filtered(){return rows.filter(r=>(!$('season').value||String(r.season)===$('season').value)&&(!$('type').value||r.track_type===$('type').value)&&(!$('track').value||r.track===$('track').value));}
function table(headers,body){return body.length?`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${body.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="empty">No results match these filters. Try another season or track.</p>';}
function cards(rs){const s=summary(rs);return `<div class="cards">${[['Starts',s.starts],['Wins',s.wins],['Top 5 / Top 10',`${s.top5} / ${s.top10}`],['Average finish',fmt(s.avg)],['Laps led',fmt(s.led)]].map(([k,v])=>`<div class="card"><small>${k}</small><strong>${v}</strong></div>`).join('')}</div>`;}
function resultTable(rs){return table(['Date','Race','Track','Finish','Start','Laps led','Rating'],rs.map(r=>[esc(r.race_date),esc(r.race_name),esc(r.track),r.finish===1?'<span class="win">1</span>':fmt(r.finish),fmt(r.start),fmt(r.laps_led),fmt(r.result_driver_rating)]));}
function driversOptions(){const names=new Map(rows.map(r=>[r.driver_key,r.driver]));return [...names].sort((a,b)=>a[1].localeCompare(b[1])).map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');}
function bindControls(){const list=driversOptions();if(view==='drivers'||view==='compare'){const ids=[...new Set(rows.map(r=>r.driver_key))];if(!ids.includes(driver))driver=rows.find(r=>r.driver==='Kyle Larson')?.driver_key??ids[0];if(!ids.includes(opponent)||opponent===driver)opponent=rows.find(r=>r.driver==='Denny Hamlin'&&r.driver_key!==driver)?.driver_key??ids.find(id=>id!==driver);$('controls').innerHTML=`<label>${view==='compare'?'Driver A':'Find a driver'}<select id="driver">${list}</select></label>${view==='compare'?`<label>Driver B<select id="opponent">${list}</select></label>`:''}`;$('driver').value=driver;$('driver').onchange=()=>{driver=$('driver').value;render();};if($('opponent')){$('opponent').value=opponent;$('opponent').onchange=()=>{opponent=$('opponent').value;render();};}}else if(view==='leaders'){$('controls').innerHTML='<label>Rank by<select id="metric"><option value="wins">Wins</option><option value="avg">Average finish (lowest first)</option><option value="top5">Top 5 finishes</option><option value="top10">Top 10 finishes</option><option value="led">Laps led</option><option value="rating">Average driver rating</option></select></label>';$('metric').value=metric;$('metric').onchange=()=>{metric=$('metric').value;render();};}else $('controls').innerHTML=view==='tracks'?'<p class="note">Select a track above to see its driver leaderboard and race history.</p>':'';}
function leaderboard(rs){const groups=new Map();for(const r of rs){if(!groups.has(r.driver_key))groups.set(r.driver_key,[]);groups.get(r.driver_key).push(r);}const leaders=[...groups.values()].map(g=>({name:g[0].driver,...summary(g)})).sort((a,b)=>a[metric]==null?1:b[metric]==null?-1:(metric==='avg'?a.avg-b.avg:b[metric]-a[metric])||a.avg-b.avg||a.name.localeCompare(b.name));return table(['Rank','Driver','Starts','Wins','Top 5','Top 10','Avg finish','Laps led','Avg rating'],leaders.map((s,i)=>[i+1,esc(s.name),s.starts,s.wins,s.top5,s.top10,fmt(s.avg),fmt(s.led),fmt(s.rating)]));}
function recent(rs){const races=[...new Map(rs.map(r=>[r.race_key,r])).values()].sort((a,b)=>b.race_date.localeCompare(a.race_date)||b.race_number-a.race_number);return table(['Date','Race','Track','Type','Winner','Entries'],races.map(r=>{const field=rs.filter(x=>x.race_key===r.race_key);return [esc(r.race_date),`<button class="race-button" data-race="${esc(r.race_key)}">${esc(r.race_name)}</button>`,esc(r.track),esc(r.track_type),esc(field.find(x=>x.finish===1)?.driver??'—'),field.length];}));}
function render(){const rs=filtered(),name=id=>rows.find(r=>r.driver_key===id)?.driver??'';let html='';if(view==='drivers'){const dr=rs.filter(r=>r.driver_key===driver).sort((a,b)=>b.race_date.localeCompare(a.race_date));html=`<h2>${esc(name(driver))}</h2><p>Driver form across the selected races.</p>${cards(dr)}${resultTable(dr)}`;}else if(view==='compare'){if(driver===opponent){html='<p class="empty">Choose two different drivers to compare.</p>';}else{const c=compare(rs,driver,opponent);html=`<h2>${esc(name(driver))} vs. ${esc(name(opponent))}</h2><p>${c.pairs.length} shared races · ${esc(name(driver))} ahead ${c.a} times · ${esc(name(opponent))} ahead ${c.b} times · ${c.ties} ties</p><p class="note">Both summaries use only races where both drivers competed.</p><div class="split"><div><h3>${esc(name(driver))}</h3>${cards(c.pairs.map(p=>p[0]))}</div><div><h3>${esc(name(opponent))}</h3>${cards(c.pairs.map(p=>p[1]))}</div></div>${table(['Date','Track',name(driver),name(opponent),'Ahead'],c.pairs.sort((a,b)=>b[0].race_date.localeCompare(a[0].race_date)).map(([a,b])=>[esc(a.race_date),esc(a.track),a.finish,b.finish,esc(a.finish<b.finish?a.driver:b.finish<a.finish?b.driver:'Tie')]))}`;}}else if(view==='leaders'){html=`<h2>The leaderboard</h2><p>All drivers in the selected races. Average finish and rating include every available start; no minimum starts threshold.</p>${leaderboard(rs)}`;}else if(view==='tracks'){html=`<h2>${esc($('track').value||'All tracks')}</h2>${cards(rs)}<p class="note">Starts counts driver entries. Wins counts winning entries across the selected races.</p>${leaderboard(rs)}<h2>Race history</h2>${recent(rs)}`;}else{html=`<h2>Recent races</h2><p>Newest races in your current export, with complete finishing orders.</p>${recent(rs)}`;}if(race){const field=rs.filter(r=>r.race_key===race).sort((a,b)=>a.finish-b.finish);if(field.length)html+=`<h2>${esc(field[0].race_name)} · ${esc(field[0].race_date)}</h2>${table(['Finish','Driver','Start','Laps','Laps led','Status'],field.map(r=>[r.finish,esc(r.driver),fmt(r.start),fmt(r.laps_completed),fmt(r.laps_led),esc(r.status)]))}`;}$('results').innerHTML=html;document.querySelectorAll('[data-race]').forEach(b=>b.onclick=()=>{race=b.dataset.race;render();$('results').querySelector('h2:last-of-type')?.scrollIntoView({behavior:'smooth'});});}
async function init(){try{const response=await fetch('./data/stats.json',{cache:'no-cache'});if(!response.ok)throw Error('Data unavailable');const data=await response.json();if(data.schemaVersion!==1||!data.rows.length)throw Error('Unsupported dataset');rows=data.rows;const seasons=unique(rows,'season').sort((a,b)=>b-a);$('season').innerHTML=options(seasons,'All seasons');$('type').innerHTML=options(unique(rows,'track_type'),'All track types');$('track').innerHTML=options(unique(rows,'track'),'All tracks');$('coverage').textContent=`${data.raceCount} races · ${unique(rows,'season').join('–')} · Results through ${data.latestRaceDate} · ${rows.length.toLocaleString()} driver starts`;for(const id of ['season','type','track'])$(id).onchange=()=>{race='';render();};$('reset').onclick=()=>{for(const id of ['season','type','track'])$(id).value='';race='';render();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;race='';document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));bindControls();render();});bindControls();render();}catch(e){$('coverage').textContent='The race data could not be loaded.';$('results').innerHTML='<p class="empty">Please reload the page. If the problem persists, check that data/stats.json was published with the site.</p>';console.error(e);}}
init();
