import {esc,safeLink,json,table,today,centralTime,centralStamp} from './family-utils.js';
import {dadHTML,loadLineup} from './dad.js';
import {mountWeather,cancelWeather} from './weather.js';
const $=id=>document.getElementById(id);
let active='',request=0,statsPromise;
function brief(r){return r?`<article class="family-panel"><p class="eyebrow">NEXT CUP RACE</p><h3>${esc(r.track)}</h3><p>${esc(r.date)} · ${esc(centralTime(r.time)||'Time to be confirmed')} · ${esc(r.tv||'TV to be confirmed')}</p></article>`:'<p>No upcoming race is listed. The next season’s schedule needs to be added.</p>';}
async function renderFamily(view){active=view;const ticket=++request;cancelWeather();document.querySelector('.filters').hidden=true;$('controls').innerHTML='';$('results').innerHTML='<p role="status">Loading…</p>';try{const [config,schedule]=await Promise.all([json('./data/family.json'),json('./data/schedule.json')]);if(active!==view||request!==ticket)return;const race=schedule.races.find(r=>r.date>=today());if(view==='schedule'){$('results').innerHTML=`<h2>Cup Series schedule · ${schedule.season}</h2>${brief(race)}<p>All start times are Central Time (CST/CDT). Checked ${esc(schedule.checkedAt)}; subject to change.</p>${table(['Date','Track','Start (CT)','TV'],schedule.races.map(r=>[r.date,r.track,centralTime(r.time)||'—',r.tv||'—']))}<a href="${esc(safeLink(schedule.source))}" target="_blank" rel="noopener">Official NASCAR schedule ↗</a>`;}else if(view==='dad'){statsPromise??=json('./data/stats.json').catch(e=>{statsPromise=null;throw e;});const stats=await statsPromise;if(active!==view||request!==ticket)return;$('results').innerHTML=dadHTML(config,stats,schedule,race,brief(race));const current=()=>active==='dad'&&request===ticket;$('refresh-qualifying').onclick=()=>loadLineup(race,current);loadLineup(race,current);}else if(view==='fantasy'){const f=config.fantasy;$('results').innerHTML=`<h2>${esc(f.title)}</h2><div class="family-links"><a class="race-button" href="${esc(safeLink(f.sourceUrl))}" target="_blank" rel="noopener">Open live Larcom League ↗</a><button id="refresh-fantasy">Reload published snapshot ↻</button></div><p>Standings snapshot ${esc(centralStamp(f.updatedAt)||'not available')}. Reload checks this site’s published data; open the league for live standings.</p>${f.standings.length?table(['Rank','Team','Points','Last race'],[...f.standings].sort((a,b)=>b.points-a.points).map((r,i)=>[i+1,r.name,r.points,r.lastRacePoints??'—'])):'<p>Standings have not been imported.</p>'}`;$('refresh-fantasy').onclick=()=>renderFamily('fantasy');}else mountWeather(config.weather,()=>active==='weather'&&request===ticket);}catch{if(active===view&&request===ticket)$('results').innerHTML='<p class="empty">This section could not load. Please try again.</p>';}}
const extra=['fantasy','schedule','dad','weather'];$('tabs').insertAdjacentHTML('beforeend',extra.map((v,i)=>`<button data-view="${v}" aria-pressed="false">${['Fantasy League','Schedule','Dad’s Corner','Weather'][i]}</button>`).join(''));
$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;if(extra.includes(b.dataset.view)){e.stopImmediatePropagation();document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderFamily(b.dataset.view);}else{active='';request++;cancelWeather();document.querySelector('.filters').hidden=false;}},true);

